# Netlist Viewer TCL File
set_family -name SmartFusion2
top_module -name SF2_MSS_sys
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/Actel/DirectCore/CoreResetP/7.0.104/rtl/vhdl/core/coreresetp_pcie_hotreset.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/Actel/DirectCore/CoreResetP/7.0.104/rtl/vhdl/core/coreresetp.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/work/SF2_MSS_sys_sb/CCC_0/SF2_MSS_sys_sb_CCC_0_FCCC.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/Actel/SgCore/OSC/2.0.101/osc_comps.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/work/SF2_MSS_sys_sb/FABOSC_0/SF2_MSS_sys_sb_FABOSC_0_OSC.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/work/SF2_MSS_sys_sb_MSS/SF2_MSS_sys_sb_MSS_syn.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/work/SF2_MSS_sys_sb_MSS/SF2_MSS_sys_sb_MSS.vhd}
addfile -view RTL -lib COREAPB3_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/Actel/DirectCore/CoreAPB3/4.1.100/rtl/vhdl/core/coreapb3_muxptob3.vhd}
addfile -view RTL -lib COREAPB3_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/Actel/DirectCore/CoreAPB3/4.1.100/rtl/vhdl/core/coreapb3_iaddr_reg.vhd}
addfile -view RTL -lib COREAPB3_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/Actel/DirectCore/CoreAPB3/4.1.100/rtl/vhdl/core/coreapb3.vhd}
addfile -view RTL -lib COREGPIO_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/Actel/DirectCore/CoreGPIO/3.1.101/rtl/vhdl/core/coregpio_pkg.vhd}
addfile -view RTL -lib COREGPIO_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/Actel/DirectCore/CoreGPIO/3.1.101/rtl/vhdl/core/coregpio.vhd}
addfile -view RTL -lib COREPWM_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/Actel/DirectCore/corepwm/4.3.101/rtl/vhdl/core/pwm_gen.vhd}
addfile -view RTL -lib COREPWM_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/Actel/DirectCore/corepwm/4.3.101/rtl/vhdl/core/reg_if.vhd}
addfile -view RTL -lib COREPWM_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/Actel/DirectCore/corepwm/4.3.101/rtl/vhdl/core/tach_if.vhd}
addfile -view RTL -lib COREPWM_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/Actel/DirectCore/corepwm/4.3.101/rtl/vhdl/core/timebase.vhd}
addfile -view RTL -lib COREPWM_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/Actel/DirectCore/corepwm/4.3.101/rtl/vhdl/core/t_corepwm_pkg.vhd}
addfile -view RTL -lib COREPWM_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/Actel/DirectCore/corepwm/4.3.101/rtl/vhdl/core/corepwm.vhd}
addfile -view RTL -lib COREUARTAPB_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/work/SF2_MSS_sys_sb/CoreUARTapb_0/rtl/vhdl/core/Clock_gen.vhd}
addfile -view RTL -lib COREUARTAPB_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/work/SF2_MSS_sys_sb/CoreUARTapb_0/rtl/vhdl/core/Rx_async.vhd}
addfile -view RTL -lib COREUARTAPB_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/work/SF2_MSS_sys_sb/CoreUARTapb_0/rtl/vhdl/core/Tx_async.vhd}
addfile -view RTL -lib COREUARTAPB_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/work/SF2_MSS_sys_sb/CoreUARTapb_0/rtl/vhdl/core/fifo_256x8.vhd}
addfile -view RTL -lib COREUARTAPB_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/work/SF2_MSS_sys_sb/CoreUARTapb_0/rtl/vhdl/core/coreuart_pkg.vhd}
addfile -view RTL -lib COREUARTAPB_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/work/SF2_MSS_sys_sb/CoreUARTapb_0/rtl/vhdl/core/CoreUART.vhd}
addfile -view RTL -lib COREUARTAPB_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/work/SF2_MSS_sys_sb/CoreUARTapb_0/rtl/vhdl/core/CoreUARTapb.vhd}
addfile -view RTL -lib COREAPB3_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/Actel/DirectCore/CoreAPB3/4.1.100/rtl/vhdl/core/components.vhd}
addfile -view RTL -lib COREGPIO_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/Actel/DirectCore/CoreGPIO/3.1.101/rtl/vhdl/core/components.vhd}
addfile -view RTL -lib COREPWM_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/Actel/DirectCore/corepwm/4.3.101/rtl/vhdl/core/components.vhd}
addfile -view RTL -lib COREUARTAPB_LIB -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/work/SF2_MSS_sys_sb/CoreUARTapb_0/rtl/vhdl/core/components.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/work/SF2_MSS_sys_sb/SF2_MSS_sys_sb.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/component/work/SF2_MSS_sys/SF2_MSS_sys.vhd}
addfile -view HIER -lib work -type EDIF -mode NONE -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/synthesis/SF2_MSS_sys.edn}
addfile -view FLAT -lib work -type AFL -mode NONE -name {C:/Users/Mike Klopfer/Documents/GitHub/Microsemi_SmartFusion2_DigikeyBoardDemo/sf2project/designer/SF2_MSS_sys/SF2_MSS_sys.afl}